from __future__ import annotations

from typing import Final

STATE_INIT: Final[str] = "INIT"
STATE_LOAD_SKILL_CATALOG: Final[str] = "LOAD_SKILL_CATALOG"
STATE_PREFILTER_SKILLS: Final[str] = "PREFILTER_SKILLS"
STATE_DISCLOSE_CONTEXT_STAGE: Final[str] = "DISCLOSE_CONTEXT_STAGE"
STATE_CALL_LLM: Final[str] = "CALL_LLM"
STATE_DECODE_DECISION: Final[str] = "DECODE_DECISION"
STATE_EXECUTE_STEP: Final[str] = "EXECUTE_STEP"
STATE_VERIFY_PROGRESS: Final[str] = "VERIFY_PROGRESS"
STATE_HANDOFF_OR_FINISH: Final[str] = "HANDOFF_OR_FINISH"
STATE_DONE: Final[str] = "DONE"
STATE_ERROR: Final[str] = "ERROR"

ALL_STATES: Final[set[str]] = {
    STATE_INIT,
    STATE_LOAD_SKILL_CATALOG,
    STATE_PREFILTER_SKILLS,
    STATE_DISCLOSE_CONTEXT_STAGE,
    STATE_CALL_LLM,
    STATE_DECODE_DECISION,
    STATE_EXECUTE_STEP,
    STATE_VERIFY_PROGRESS,
    STATE_HANDOFF_OR_FINISH,
    STATE_DONE,
    STATE_ERROR,
}
